algoritmo "Boas Vindas"
//Nome: Gabriel Jesus
//Data: 16/10/2024

//02)Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boas-vindas para ela:
//Exemplo:
//Qual é o seu nome? Gabriel Jesus
//Olá Gabriel Jesus, Seja Bem vindo!
var
   //Declaração de variáveis
   nome: caractere
inicio
   //Solicitação de dados ao usuário
   Escreva("Qual é o seu nome? ")
   leia(nome)
   Escreval("Olá ", nome, ", Seja Bem vindo!")

fimalgoritmo